defaults:
  - metric: pointing_game
  - model: vit
  - method: tis
  - dataset: ilsvrc2012_subset
  # - dataset: ilsvrc2012_bboxes_subset 
  - transform: ilsvrc2012_albumentations
  - optional method_model: ${method}_${model}
  - optional metric_dataset: ${metric}_${dataset}
  - _self_  

seed: 12345
no_target: false
# input_npz: npz/${model.name}_${method.name}_heatmap
input_npz: /kaggle/working/tis/npz/vit_b16_agc_heatmap
output_csv_dir: csv/
metric_batch_size: 8
start_idx: -1
end_idx: -1