defaults:
  - model: vit
  - method: better_agc
  - transform: ilsvrc2012
  - optional method_model: ${method}_${model}
  - _self_

seed: 12345
input_file: ILSVRC2012_val_00000125.jpg
output_file: output.jpg
class_idx: null
