defaults:
  - model: vit
  - method: tis
  - dataset: ilsvrc2012_subset
  - transform: ilsvrc2012_albumentations
  - optional method_model: ${method}_${model}
  - _self_

seed: 12345
output_npz: npz/${model.name}_${method.name}_heatmap.npz
no_target: false
start_idx: -1
end_idx: -1
get_scores: false
score_normalization_function: minmax
